file(GLOB_RECURSE ALL_HEADERS "${SOURCE_DIR}/*.hpp")
foreach(HEADER ${ALL_HEADERS})
    get_filename_component(FILENAME ${HEADER} NAME)
    if(NOT FILENAME STREQUAL "config.hpp")
        file(RELATIVE_PATH REL_PATH ${SOURCE_DIR} ${HEADER})
        get_filename_component(REL_DIR ${REL_PATH} DIRECTORY)
        file(MAKE_DIRECTORY "${DEST_DIR}/${REL_DIR}")
        file(COPY ${HEADER} DESTINATION "${DEST_DIR}/${REL_DIR}")
    endif()
endforeach()